import type { CSSProperties } from 'react';

/**
 * Shared chrome for the Medusa layer editors (Persona, Theme, Voice, Toolbox,
 * Packs). Every value comes from a CSS variable so the Theme editor's live
 * preview repaints these panes along with the rest of the app.
 */
export const s: Record<string, CSSProperties> = {
  pane: { display: 'flex', flexDirection: 'column', gap: 14, minHeight: 280 },
  section: { display: 'flex', flexDirection: 'column', gap: 8 },
  label: {
    fontSize: 11,
    fontWeight: 600,
    color: 'var(--text-secondary)',
    textTransform: 'uppercase',
    letterSpacing: '0.08em',
  },
  card: {
    background: 'rgba(255,255,255,0.04)',
    border: '1px solid var(--border)',
    borderRadius: 8,
    padding: 12,
    display: 'flex',
    flexDirection: 'column',
    gap: 10,
  },
  field: { display: 'flex', flexDirection: 'column', gap: 4 },
  fieldLabel: { fontSize: 12, color: 'var(--text-secondary)' },
  input: {
    width: '100%',
    background: 'var(--glass-bg)',
    color: 'var(--text-primary)',
    border: '1px solid var(--border-light)',
    borderRadius: 6,
    padding: '6px 8px',
    fontSize: 12,
    outline: 'none',
    boxSizing: 'border-box',
  },
  textarea: {
    width: '100%',
    minHeight: 120,
    background: 'var(--glass-bg)',
    color: 'var(--text-primary)',
    border: '1px solid var(--border-light)',
    borderRadius: 6,
    padding: '8px',
    fontSize: 12,
    lineHeight: 1.5,
    fontFamily: 'var(--font)',
    resize: 'vertical',
    outline: 'none',
    boxSizing: 'border-box',
  },
  pre: {
    margin: 0,
    maxHeight: 220,
    overflow: 'auto',
    background: 'var(--bg-tertiary)',
    border: '1px solid var(--border)',
    borderRadius: 6,
    padding: 10,
    fontSize: 11,
    lineHeight: 1.5,
    color: 'var(--text-secondary)',
    fontFamily: 'var(--font-mono)',
    whiteSpace: 'pre-wrap',
  },
  row: { display: 'flex', alignItems: 'center', gap: 10 },
  spread: { display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 10 },
  btn: {
    padding: '6px 12px',
    fontSize: 11,
    fontWeight: 600,
    color: 'var(--text-primary)',
    background: 'rgba(255,255,255,0.08)',
    border: '1px solid var(--border-light)',
    borderRadius: 6,
    cursor: 'pointer',
  },
  btnPrimary: {
    padding: '6px 12px',
    fontSize: 11,
    fontWeight: 600,
    color: '#fff',
    background: 'var(--accent)',
    border: '1px solid var(--accent)',
    borderRadius: 6,
    cursor: 'pointer',
  },
  btnDanger: {
    padding: '6px 12px',
    fontSize: 11,
    fontWeight: 600,
    color: 'var(--danger)',
    background: 'rgba(192,57,43,0.12)',
    border: '1px solid rgba(192,57,43,0.3)',
    borderRadius: 6,
    cursor: 'pointer',
  },
  hint: { fontSize: 11, color: 'var(--text-muted)', lineHeight: 1.5, margin: 0 },
  note: { fontSize: 11, color: 'var(--accent)', margin: 0 },
  error: { fontSize: 11, color: 'var(--danger)', margin: 0, lineHeight: 1.5 },
  listRow: {
    display: 'flex',
    alignItems: 'center',
    gap: 10,
    padding: '8px 0',
    borderBottom: '1px solid var(--border)',
  },
  listText: { display: 'flex', flexDirection: 'column', gap: 1, minWidth: 0, flex: 1 },
  listLabel: { fontSize: 12.5, fontWeight: 600, color: 'var(--text-primary)' },
  listDetail: {
    fontSize: 11,
    color: 'var(--text-muted)',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  select: {
    background: 'var(--glass-bg)',
    color: 'var(--text-primary)',
    border: '1px solid var(--border-light)',
    borderRadius: 6,
    padding: '4px 6px',
    fontSize: 11,
    cursor: 'pointer',
    outline: 'none',
  },
  slider: { width: '100%', accentColor: 'var(--accent)', cursor: 'pointer' },
  swatchGrid: { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 10 },
  swatchRow: { display: 'flex', alignItems: 'center', gap: 8 },
  colorInput: {
    width: 34,
    height: 26,
    padding: 0,
    border: '1px solid var(--border-light)',
    borderRadius: 6,
    background: 'transparent',
    cursor: 'pointer',
  },
  avatar: {
    width: 48,
    height: 48,
    borderRadius: '50%',
    objectFit: 'cover',
    border: '1px solid var(--border-light)',
  },
  avatarBlank: {
    width: 48,
    height: 48,
    borderRadius: '50%',
    border: '1px dashed var(--border-light)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: 10,
    color: 'var(--text-muted)',
  },
};

/** The 32x18 pill toggle used across these panes. */
export const toggleStyles = {
  track: (on: boolean): CSSProperties => ({
    width: 32,
    height: 18,
    borderRadius: 9,
    border: 'none',
    cursor: 'pointer',
    padding: 2,
    display: 'flex',
    alignItems: 'center',
    flexShrink: 0,
    background: on ? 'var(--accent)' : 'rgba(255,255,255,0.14)',
    transition: 'background 0.15s',
  }),
  knob: (on: boolean): CSSProperties => ({
    width: 14,
    height: 14,
    borderRadius: '50%',
    background: '#fff',
    transform: on ? 'translateX(14px)' : 'translateX(0)',
    transition: 'transform 0.15s',
  }),
};
